name: Update Data

on:
  push:
    branches:
      - main
  schedule:
    - cron: '24 0 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

    steps:

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build
        run: go build -o ./bin/data -mod vendor -trimpath -ldflags '-s -w' ./app/data/

      - name: Prepare secrets
        run: echo "${{ secrets.SECRETS_YAML }}" > secrets.yaml

      - name: Run mirror-data
        run: ./bin/data

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ismdeep
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push back
        if: env.BRANCH_NAME == 'main'
        run: |
          set -e
          if [ "$(git status --short | wc -l)" != "0" ]; then
            git config user.name "L. Jiang"
            git config user.email "l.jiang.1024@gmail.com"
            git add .
            git commit -am "docs: update data via github workflow"
            git push origin HEAD:main
            docker buildx build --platform linux/amd64 --progress plain --pull --push -t ismdeep/mirror-server:latest -f ./app/mirror/Dockerfile .
          fi
