name: Update Data

on:
  push:
    branches:
      - main
  schedule:
    - cron: '24 0 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

    steps:

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.6'

      - name: Install rclone
        run: make install-rclone

      - name: Build
        run: make bin

      - name: Prepare secrets
        run: echo "${{ secrets.SECRETS_YAML }}" > secrets.yaml

      - name: Run mirror-data
        run: ./bin/data

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ismdeep
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push back
        if: env.BRANCH_NAME == 'main'
        run: make publish
